<package format="3">
  <name>people</name>
  <version>1.1.2</version>
  <description>The people stack holds algorithms for perceiving people from a number of sensors.</description>
  <maintainer email="dan@lazewatsky.com">Dan Lazewatsky</maintainer>
  <license>BSD</license>

  <url type="website">http://ros.org/wiki/people</url>
  <author>Caroline Pantofaru</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>face_detector</depend>
  <depend>leg_detector</depend>
  <depend>people_msgs</depend>
  <depend>people_tracking_filter</depend>
  <depend>people_velocity_tracker</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
