<?xml version="1.0"?>
<package format="3">
  <name>people_tracking_filter</name>
  <version>1.1.2</version>
  <description>
    A collection of filtering tools for tracking people's locations
  </description>
  <author>Caroline Pantofaru</author>
  <maintainer email="davidvlu@gmail.com">David V. Lu!!</maintainer>
  <license>BSD</license>
  <url>http://ros.org/wiki/people_tracking_filter</url>

  <!-- Build tool and dependencies for ROS2 -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>bfl</depend>
  <depend>geometry_msgs</depend>
  <depend>message_filters</depend>
  <depend>people_msgs</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf_transformations</depend>
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>
  <export>
    <build_type>ament_cmake</build_type>
    <nav2_core plugin="${prefix}/prsbc_pursuit_controller.xml" />
  </export>
</package>
